// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreatePromotion(ctx context.Context, arg CreatePromotionParams) (sql.Result, error)
	GetPromotion(ctx context.Context, id int32) (Promotion, error)
	IsPromotionCodeTaken(ctx context.Context, arg IsPromotionCodeTakenParams) (bool, error)
	ListPromotions(ctx context.Context) ([]Promotion, error)
}

var _ Querier = (*Queries)(nil)
